import type { Metadata } from "next";

import "./globals.css";
import SessionProviderComponent from "./components/SessionProviderComponent";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <SessionProviderComponent>
      
        {children}
        </SessionProviderComponent>
      </body>
    </html>
  );
}
